//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentalStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public string bid { get; set; }
        public Nullable<System.DateTime> importDate { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public string pid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
