//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentalStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepartmentalStoreManagementEntities : DbContext
    {
        public DepartmentalStoreManagementEntities()
            : base("name=DepartmentalStoreManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DepartmentalStore> DepartmentalStores { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffAccount> StaffAccounts { get; set; }
        public virtual DbSet<ImageReference> ImageReferences { get; set; }
        public virtual DbSet<MonthlyIncome> MonthlyIncomes { get; set; }
    }
}
