//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentalStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAccount
    {
        public string username { get; set; }
        public byte[] passwordHash { get; set; }
        public string sid { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
